name: Example Using Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    name: Demo Using Secrets
    steps:
    - name: Echo Out The Secret
      env:
        bsides_secret: ${{ secrets.demo_secret }}
      run: wc -c <<< "$bsides_secret"; tr a-z A-Z <<< "$bsides_secret"
