name: Example Using Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    name: swap case once
    steps:
    - name: Swap the secret case 1x
      env:
        bsides_secret: ${{ secrets.demo_secret }}
      run: wc -c <<< "$bsides_secret"; tr a-zA-Z A-Za-z <<< "$bsides_secret"
